name: CI + CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: |
          echo "Compiling..."
          echo "Compiled!"

  DeployDev:
    needs: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment:
      name: Development
      url: "http://dev.example.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          echo "Deploying to dev..."
          echo "Deployed to dev!"

  DeployDevBusiness:
    needs: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment:
      name: Development_business_app
      url: "http://dev.business.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          echo "Deploying to dev business..."
          echo "Deployed to dev business!"

  DeployStaging:
    needs: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: Staging
      url: "http://staging.example.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          echo "Build an push image: build:$GITHUB_SHA"

      - name: Deploy
        run: |
          echo "Deploying to staging..."
          echo "Deployed to staging!"

  DeployStagingBusiness:
    needs: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: Staging_business_app
      url: "http://staging.business.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          echo "Build an push image: business-image:$GITHUB_SHA"

      - name: Deploy
        run: |
          echo "Deploying to staging business..."
          echo "Deployed to staging business!"

  DeployProd:
    needs: DeployStaging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: Production
      url: "http://example.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          echo "Deploying to production, image:$GITHUB_SHA"
          echo "Deployed to production!"

  DeployProdBusiness:
    needs: DeployStagingBusiness
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: Production_business_app
      url: "http://business.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          echo "Deploying to production business, business-image:$GITHUB_SHA"
          echo "Deployed to production business!"
